# Configure Makefile for the SPriG library

# Comment/uncomment the following line to disable/enable build options
# (See README for more info)
C_COMP = y
#QUIET = y


# Compilers (C and C++)
CC=gcc
CXX=g++

# Make sure sdl-config is available
HAVE_SDL =$(shell if (sdl-config --version) < /dev/null > /dev/null 2>&1; then echo "y"; else echo "n"; fi;)
ifeq ($(HAVE_SDL),n)
  $(error ERROR: Can't find SDL! Make sure that you have SDL [ http://www.libsdl.org/ ] and its development files installed)
endif

# Where should SPriG be installed?
PREFIX =$(shell sdl-config --prefix)

# Where should the headerfiles be installed?
PREFIX_H =$(shell sdl-config --prefix)/include/SDL

# Flags passed to the compiler
CFLAGS =-Wall -O3 -ffast-math -s
SPRIG_CFLAGS =$(shell sdl-config --cflags)
# Uncomment to make some more optimizations
#CFLAGS =-Wall -O9 -ffast-math -march=i686


# Libs config
SPRIG_LIBS =$(shell sdl-config --libs) -lstdc++


